main:
  - title: "TFB: Towards Comprehensive and Fair Benchmarking of Time Series Forecasting Methods"
    descript: "A comprehensive and fair benchmarking framework for time series forecasting methods, addressing key challenges in evaluation and comparison."
    pdf: https://arxiv.org/pdf/2403.20150
    code: https://github.com/decisionintelligence/TFB
    image: ./assets/img/TFB.png
    others: '<img src="https://img.shields.io/github/stars/decisionintelligence/TFB?style=social" />'

  - title: "Robot Automatic Aiming System"
    descript: "An advanced automatic aiming system for robots, enhancing precision and efficiency in target acquisition. This project was for the <a href='https://www.robomaster.com/zh-CN' target='_blank'>RoboMaster</a> competition."
    code: https://github.com/decisionintelligence/TFB
    video: https://www.bilibili.com/video/BV1ke4y1X7gX/
    image: ./assets/img/robomaster.gif

  - title: "RAG-Powered Research Assistant"
    descript: "A research assistant tool leveraging Retrieval-Augmented Generation (RAG) to provide accurate and context-aware responses to user queries, enhancing research efficiency."
    image: ./assets/img/assistant.gif
    code: https://github.com/DevCrafterLZY/chatR-ecnu
