  - title: "TFB: Towards Comprehensive and Fair Benchmarking of Time Series Forecasting Methods"
    pdf: https://arxiv.org/pdf/2403.20150
    code: https://github.com/decisionintelligence/TFB
    image: ./assets/img/TFB.png
    others: '<img src="https://img.shields.io/github/stars/decisionintelligence/TFB?style=social" />'